import * as h from "../helpers";
var distance = (b1: number[], b2:number[]) : number => Math.sqrt(Math.pow(b1[0]-b2[0],2) + Math.pow(b1[1] -b2[1],2) + Math.pow(b1[2]-b2[2],2));
var dists = (scanner:number[][]) : number[][] => scanner.map(s1 => scanner.map(s2 => distance(s1,s2)));
console.time("day 19");
var scanners = h.read(19,'scanners.txt').subfilter(l => !l.includes('scanner')).split(',').tonum();
h.print(scanners.slice(0,2));
h.print(scanners.map(s => s.length));
h.print('');
h.print(dists(scanners[0]).mape(d => Math.round(d)).printcolor(x => x==0,'r',','));
console.timeEnd("day 19");